---
title: "Zonal Statistics on NLCD land  classes in Montana"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Read packages and data
```{r packages_and_data}

library(tidyverse)
library(raster)
library(parallel)
library(reshape2)

# setwd("~/StrandedLand/stranded_repo") # Bren R server
setwd("~/Desktop/StrandedLand/stranded_repo") # Desktop

nlcd_mt <- raster("../R_output_files/nlcd/nlcd_mt.tif")
values(nlcd_mt)[values(nlcd_mt)==0] <- NA

nlcd_mt_stranded <- raster("../R_output_files/nlcd/nlcd_mt_stranded.tif")
nlcd_gb <- raster("../R_output_files/nlcd/nlcd_gb.tif")
nlcd_gb_stranded <- raster("../R_output_files/nlcd/nlcd_gb_stranded.tif")

raster_list <- as.list(nlcd_mt,nlcd_mt_stranded,nlcd_gb,nlcd_gb_stranded)
```


### 2. Look at land in each NLCD class (reclassified)
```{r zonal_stats}

zonal_stats = as.data.frame(matrix(nrow = 10, ncol = 2))
colnames(zonal_stats) = c("value","desc")

zonal_stats[,1] = c(11,12,20,25,30,40,50,70,80,90)
zonal_stats[,2] = c("open water","ice or snow","low intensity development","high intensity development","barren","forest","shrub","herbaceous","cropland","wetlands")


timestamp() ### 

for(i in 1:length(raster_list)){
  
  print(i)
  tmp_df <- as.data.frame(freq(raster_list[[i]]))
  zonal_stats = merge(zonal_stats,tmp_df,by = "value",all=TRUE)
  # remove(tmp_df)
  
}

timestamp() ### 

colnames(zonal_stats) = c("value", "nlcd_description","mt","mt_stranded","gb","gb_stranded")
zonal_stats = filter(zonal_stats, !is.na(value)&value != 0)

# dir.create("./output/csv")
write_csv(zonal_stats,"../R_output_files/csv/nlcd_mt_overview2.csv")
```


### Compare stranded land composition to randomly selected cells
```{r compare_stranded_to_random}

# Create data.frame
str_rand_compare = data.frame(value = zonal_stats$value,
                              nlcd_desc = zonal_stats$nlcd_description,
                              nlcd_mt = zonal_stats$mt,
                              nlcd_stranded = zonal_stats$mt_stranded)

# Determine # of stranded land Raster cells that are not equal to NA
ncell_str <- ncell(nlcd_mt_stranded[nlcd_mt_stranded>0])

# Select values from the same number of calls at random from the Montana NLCD raster
random_nlcd <- sampleRandom(nlcd_mt,na.rm = TRUE, size = ncell_str)

# Check spatial randomness in QGIS
# writeOGR(obj = random_nlcd,dsn = "../R_output_files/",layer = "random_oints",driver = "ESRI Shapefile")

random_nlcd <- as.data.frame(table(random_nlcd))

str_rand_compare$nlcd_random = random_nlcd$Freq

write_csv(str_rand_compare,"../R_output_files/csv/summary2.csv")
```

Plot Comparison
```{r fig.height=5, fig.width=7}

str_rand_melt <- melt(str_rand_compare,id.vars = 1:2)
colnames(str_rand_melt) <- c("nlcd_value","nlcd_desc","nlcd_selection","freq")
str_rand_melt <- filter(str_rand_melt, nlcd_selection != 'nlcd_mt')

ncell_mt <- ncell(nlcd_mt[nlcd_mt>0])

# write_csv(str_rand_compare,"../R_output_files/csv/summary.csv")

ggplot(str_rand_melt,aes(x = nlcd_desc,y = freq/10000, fill = nlcd_selection)) +
  geom_col(position = "dodge") +
  theme_bw()+
  theme(strip.text = element_blank(),
        axis.text.x = element_text(face="bold",size=11,angle=45,hjust=1),
        legend.position = "top",
        legend.text = element_text(size=12))+
  labs(fill = "",subtitle = "Number of cells = 954,703")+
  xlab("NLCD Class Description")+
  ylab("Frequency of NLCD class in associated raster\n(number of raster cells x10,000 - 270-meter resolution)")+
  scale_fill_discrete(label = c("Stranded Land","Random Selection"))

ggsave("../R_output_files/stranded_random_comparison.png", width = 9, height = 8)

```


### 3. Look at land area of each NLCD class in Montana, GB, and stranded lands at each extent 
```{r total_land}

zonal_stats_area = zonal_stats[1:10,]
zonal_stats_area[is.na(zonal_stats_area)] = 0
zonal_stats_area[,3:6] <- round(zonal_stats_area[,3:6]*(270^2)*0.000247,3)

write_csv(zonal_stats_area, "../R_output_files/csv/nlcd_mt_area.csv")

total_land = as.data.frame(matrix(ncol=4,nrow=1))
for(i in 3:ncol(zonal_stats_area)){
  
  total_land[1,i-2] = round(sum(zonal_stats_area[,i]),3)
  
}
colnames(total_land) = c("mt","mt_stranded","gb","gb_stranded")

write_csv(total_land,"../R_output_files/csv/nlcd_mt_totalArea.csv")
```


### 4. Look at the percentage of each land class tied up in stranded land
```{r percentages}

zonal_stats_props = zonal_stats_area %>% 
  group_by(value,nlcd_description) %>% 
  summarise(prop_stranded_mt = round(mt_stranded/mt*100,2),
            prop_stranded_gb = round(gb_stranded/gb*100,2))

write_csv(zonal_stats_props, "../R_output_files/csv/nlcd_area_percentages.csv")
```

