    ---
title: "Preparing resistance layers for Circuitscape"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 2. Creating buffered roads raster
```{r}

##### Filter Roads Shapefile for Major interstates #####
roads_NHS = roads %>% 
  # Filter Roads shapefile for major interstates
  filter(ROADTYPE == "NHS INTERSTATE") %>% 
  # Select useful attributes
  select(SOURCEID,ROADTYPE) %>% 
  # Turn back into spatial lines
  as(.,"Spatial") %>% 
  gLineMerge()

# Add a 200-m buffer to major interstates
roads_NHS_buffer = gBuffer(roads_NHS,width = 200) %>% 
  st_as_sf()

## Major Highways
roads_PA = roads %>% 
  filter(ROADTYPE == "PRINCIPAL ARTERIAL") %>% 
  select(SOURCEID,ROADTYPE) %>% 
  as(.,"Spatial") %>% 
  gLineMerge()

roads_PA_buffer = gBuffer(roads_PA,width=100) %>% 
  st_as_sf()

## Combine NHS interstate and other highway spatial lines files
roads_buffer = rbind(roads_PA_buffer,roads_NHS_buffer) %>% 
  st_transform(.,crs(mt_counties)) %>% 
  as(.,"Spatial")

ras <- mt_nlcd
values(ras) <- NA

roads_raster <- rasterize(x = roads_buffer,y = ras,fun = 'first')

values(roads_raster)[values(roads_raster)>0] <- 100

plot(roads_buffer)
plot(roads_raster,add=TRUE,col="red")

# dir.create("../R_output_files/transpo/shp",recursive = T)

# writeOGR(obj = roads_buffer,
#          dsn = "../R_output_files/transpo/shp/",
#          layer = "roads_buffer",
#          driver = "ESRI Shapefile",
#          overwrite = T)

# writeRaster(roads_raster,"../R_output_files/transpo/roads_raster.tif",overwrite = TRUE)
```

### 3. Reclassifying NLCD for Circsuitscape Resistances
```{r reclass_for_CS}
# dir.create("../R_output_files/circuitscape/resistance/", recursive = T)

resistance_1 <- mt_nlcd
values(resistance_1)[values(resistance_1)>0] <- 1


cs_rcl_mat <- c(-Inf,11.5,NA,
                     11.5,12.5,24, # Perennial ice/snow is low resistance
                     19,21,60,
                     24,26,80,
                     29,31,24,
                     39,41,7,
                     49,51,5,
                     59,61,17,
                     79,81,61,
                     89,91,11)

resistance_nlcd <- reclassify(mt_nlcd, rcl = cs_rcl_mat)

resistance_roads_nlcd <- cover(roads_raster, resistance_nlcd)
NAvalue(resistance_roads_nlcd) <- -9999

writeRaster(resistance_1,"../R_output_files/circuitscape/resistance/resistance_1_mt.asc", format = "ascii", overwrite = T)
writeRaster(resistance_nlcd,"../R_output_files/circuitscape/resistance/resistance_nlcd_mt.asc",format = "ascii", overwrite = T)
writeRaster(resistance_roads_nlcd,"../R_output_files/circuitscape/resistance/resistance_roads_nlcd_mt.asc",format = "ascii", overwrite = T)
```


### Cropping to Gallatin-Broadwater Outline
```{r}
all_counties <- readOGR("../R_input_files/mt_counties/County.shp")
gb_outline <- readOGR("../R_input_files/mt_counties/gb_outline.shp")

```

```{r}
ras <- resistance_1
nm <- "resistance_1"

tmp_crop <- crop(ras,extent(gb_outline))

beginCluster(10)

tmp <- clusterR(tmp_crop,mask,args = list(gb_outline))
assign(paste0(nm,"_gb"),tmp)
remove(tmp,tmp_crop)

endCluster()

writeRaster(resistance_1_gb,"../R_output_files/circuitscape/resistance/resistance_1_gb.asc", format = "ascii", overwrite = T)
writeRaster(resistance_nlcd_gb,"../R_output_files/circuitscape/resistance/resistance_nlcd_gb.asc",format = "ascii", overwrite = T)
writeRaster(resistance_roads_nlcd_gb,"../R_output_files/circuitscape/resistance/resistance_roads_nlcd_gb.asc",format = "ascii", overwrite = T)

```

