---
title: "Preparing core area layers for Circuitscape"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Packages and data
```{r packages_data}

library(tidyverse)
library(rgdal)
library(raster)
library(sf)
library(parallel)
library(rgeos)
library(cleangeo)

setwd("~/StrandedLand/stranded_repo") # Bren R server
# setwd("~/Desktop/StrandedLand/stranded_repo") # Desktop

# NLCD MT raster
nlcd_mt <- raster("../R_output_files/nlcd/nlcd_mt.tif")

# Gallatin-Broadwater Outline
gb_outline <- readOGR("../R_input_files/mt_counties/gb_outline.shp") %>% 
  st_as_sf()

# Montana Outline
mt_outline <- readOGR("../R_input_files/mt_outline/StateofMontana.shp") %>% 
  spTransform(.,crs(gb_outline)) %>% 
  st_as_sf()

# Protected Areas Shapefile
pad <- readOGR("../R_input_files/mt_pad/PADUS2_0Designation_MT.shp") %>% 
  spTransform(.,crs(gb_outline))

```

### 2. Creating Core Areas
```{r core_areas}

### Clean geometries before doing anything else to shapefile.
pad_clean = cleangeo::clgeo_Clean(pad)

### Filter PAD shapefile
pad_fltr = pad_clean %>% 
  st_as_sf() %>% 
  st_simplify() %>% 
  dplyr::select(GAP_Sts,d_GAP_Sts,IUCN_Cat, GIS_Acres) %>% 
  dplyr::filter(GAP_Sts == 1|GAP_Sts == 2) 

# Convert GIS_Acres column to numeric and filter it
# pad_fltr$GIS_Acres = as.numeric(pad_fltr$GIS_Acres)

# To be used in the 
pad_fltr$dissolve = rep(1,nrow(pad_fltr))

### Back into spatial object
pad_shp = as(pad_fltr,"Spatial") 

pad_pBuf = gBuffer(pad_shp,byid=TRUE,width = 500)
pad_union = unionSpatialPolygons(pad_pBuf,IDs = pad_pBuf@data$dissolve)
pad_nBuf = gBuffer(pad_union,byid = TRUE,width = -500) %>% 
  as(.,"SpatialPolygonsDataFrame")

#### Finding centroids for Circuitscape ####
pad_disagg_sf = disaggregate(pad_nBuf) %>% 
  st_as_sf()

pad_disagg_sf$area <- as.numeric(st_area(pad_disagg_sf)*0.000247105)

pad_disagg <- dplyr::filter(pad_disagg_sf, area > 1000) %>% 
  as(.,"Spatial")

pad_centroids = st_centroid(st_as_sf(pad_disagg)) %>% 
  mutate(ras_value = 1) %>%
  dplyr::select(ras_value) %>% 
  as(.,"Spatial") 

```


```{r}
writeOGR(obj = pad_disagg, 
         dsn =  "../R_output_files/circuitscape/core_areas/pad_shp/",
         layer = "pad_union",
         driver = "ESRI Shapefile",
         overwrite = T)

writeOGR(obj = pad_shp, 
         dsn =  "../R_output_files/circuitscape/core_areas/pad_shp/",
         layer = "pad_polygons",
         driver = "ESRI Shapefile",
         overwrite = T)

writeOGR(obj = pad_centroids, 
         dsn =  "../R_output_files/circuitscape/core_areas/pad_shp/",
         layer = "pad_centroids",
         driver = "ESRI Shapefile",
         overwrite=T)
```

### Rasterize centroids
```{r}

center_ras = rasterize(pad_centroids, nlcd_mt, value = 1)
NAvalue(center_ras) <- 9999
writeRaster(center_ras$ras_value,"../R_output_files/circuitscape/center.asc",format = "ascii",overwrite=TRUE)

```

cropping to GB
```{r}

## Item to crop: 
center_ras_gbCrop <- crop(center_ras,extent(gb_outline))
center_ras_gb <- mask(center_ras_gbCrop,gb_outline)

plot(center_ras_gb$ras_value)
writeRaster(center_ras_gb$ras_value,"../R_output_files/circuitscape/center_gb.asc",format = "ascii",overwrite=TRUE)
```

