---
title: "Exploring Cadastral Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}

library(rgdal)
library(tidyverse)
library(sf)
library(cleangeo)

setwd("~/Desktop/StrandedLand/stranded_repo")
```



```{r read_in_cadastral_data}
### Loading data in to explore the cadastral data

cadastral = readOGR("../R_input_files/Cadastral20191231/montana_cadastral.shp") %>% 
  st_as_sf() %>% 
  st_simplify()

stranded = readOGR("../R_output_files/stranded_shp/montana/mt_stranded.shp") %>% 
  spTransform(.,crs(cadastral)) # Put stranded into same CRS as cadastral

timestamp()
stranded_clean = cleangeo::clgeo_Clean(stranded)
timestamp()
cadastral_clean = cleangeo::clgeo_Clean(cadastral)
timestamp()
```


Turn each shapefile into sf, select relevant attribute fields, join
```{r}

cad_sf = st_as_sf(cadastral_clean)
str_sf = st_as_sf(stranded_clean) 

cad_str_fltr = cad_str_sf %>% 
  filter(stranded == 1)
# This produces 31076 parcels that overlap with stranded parcels....

writeOGR(as(cad_str_fltr,"Spatial"),
         dsn = "../R_output_files/stranded_shp/montana/",
         layer = "stranded_cadastral",
         driver = "ESRI Shapefile")

```

Histograms of:
- TotalValue v. Stranded Land Parcels
- TotalValue v. PropType

```{r}

cadastral_slct = cadastral %>% 
  dplyr::select(PropType,GISAcres,TotalAcres,TotalBuild,TotalLandV,TotalValue)

# All cadastral data
cadastral_slct$TotalValue <- as.numeric(as.character(cadastral_slct$TotalValue))
hist(cadastral_slct$TotalValue)

# TV < $10,000
cadastral_lowTV <- cadastral_slct %>% 
  filter(TotalValue < 10000)
# 47547 rows with total value below $10,000
hist(cadastral_lowTV$TotalValue)

# TV < $100
cadastral_zeroTV <- cadastral_lowTV %>% 
  filter(TotalValue <100)
# 8542
hist(cadastral_zeroTV$TotalValue)
```

