---
title: "Marxan Layer Prep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r packages}

library(rgdal)
library(raster)
library(cleangeo)
library(tidyverse)
library(sf)

```

## Load Data for the whole state
```{r data}

# Use NLCD for CRS reference
nlcd_forCRS <- raster("../R_output_files/nlcd/nlcd_mt.tif")

# Mt outline, for trimming Stranded Land Shapefile
mt_outline <- readOGR("../R_input_files/mt_outline/StateofMontana.shp") %>% 
  spTransform(.,crs(nlcd_forCRS)) %>% 
  st_as_sf()

# Mt counties, to eventually loop through each county
# mt_counties <- readOGR("../")


#### Public Land: Stranded and Accessible ####
mt_public_land <- readOGR("../R_input_files/stranded_shp/stranded_cleanGeos.shp") %>% 
  spTransform(.,crs(nlcd_forCRS)) %>% 
  st_as_sf() %>% 
  st_intersection(.,mt_outline)

mt_stranded_public = mt_public_land %>% 
  filter(strandedal == 1)

mt_accesible_public = mt_public_land %>% 
  filter(strandedal != 1)

#### PLSS Sections ####

# Read in PLSS sections for the state of Montana
mt_sections <- readOGR("../Marxan/R_output_files/PUs/sections_wPUid.shp") %>% 
  spTransform(.,crs(nlcd_forCRS))

mt_cadastral <- readOGR("../R_input_files/Cadastral20191231/mt_cadastral_clean.shp") %>% 
  spTransform(.,crs(nlcd_forCRS))

#### Custer Outline for cropping #### 
custer_outline <- readOGR("../R_input_files/mt_counties/County.shp") %>% 
  spTransform(.,crs(nlcd_forCRS)) %>% 
  st_as_sf() %>% 
  filter(NAME == "CUSTER") %>% 
  dplyr::select(NAME)


```



## 1. Planning Units (pu.dat)
**Columns include:**

+ id
+ cost
+ status

Finding the cost (total value) of each planning unit (section)
```{r PU_cost}

# Crop mt_sections to outline of Custer County
custer_sections = mt_sections %>% 
  raster::intersect(.,as(custer_outline,"Spatial")) %>% 
  st_as_sf()

# Crop mt_cadastral to outline of Custer County
custer_cadastral = mt_cadastral %>% 
  st_as_sf() %>% 
  st_simplify() %>% 
  filter(CountyName == "Custer") %>% 
  dplyr::select(TotalValue)

# Join Cadastral data to Custer Sections
cad_section_join = st_join(x = custer_cadastral, y = custer_sections, largest = T)

## Collapsing on sections to find the total value of each section by summing the "TotalValue" of all parcels in each section
SectionValue_sf = st_as_sf(cad_section_join) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  group_by(pu_id) %>% 
  summarise(section_value = sum(as.numeric(TotalValue),na.rm=T))

## Find the cost threshold to use in Marxan
cost_threshold = sum(SectionValue_sf$section_value) # 1,149,085,848 - 1.1 billion dollars

## Merge the total section value column from the collapsed/summarised dataframe into the section data.frame
section_TV_sf = merge(custer_sections,SectionValue_sf) %>% 
  dplyr::select(id = pu_id, 
                cost = section_value)


```


Establishing the 'status' column for planning units
```{r PU_status_lockedOut}

## Accessible public land to be locked out
custer_accessible = mt_accesible_public %>% 
  filter(name == "Custer") %>% 
  select(OBJECTID) %>% 
  as(.,"Spatial")

## Determine urban areas and roads
nlcd_urban = reclassify(nlcd_forCRS,c(-Inf,19,NA,
                               20,29,20,
                               29,100,NA))

nlcd_urban_shp = rasterToPolygons(x = nlcd_urban,na.rm = T,dissolve = T)

# Check in QGIS
# writeOGR(obj = nlcd_urban_shp,
#          dsn = "../R_output_files/scratch/",
#          layer = "nlcd_urban_poly",
#          driver = "ESRI Shapefile")
#
# # All Good!

## Read in roads developed for the CS resistance layer
roads = readOGR("../R_output_files/transpo/roads_arterial_disag.shp")

## Merge roads and urban shapefiles as one 'lock out' shapefile
roads_urban_merge = raster::union(x = roads,y = nlcd_urban_shp)

## Merge the urban/roads shapefile with the accessible public land shapefile
status_locked_out <- raster::union(roads_urban_merge,custer_accessible)

status_locked_out
```



## The Conservation Feature File and 



