---
title: "Preparing core area layers for Circuitscape"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Packages and data
```{r packages_data}
library(tidyverse)
library(rgdal)
library(raster)
library(sf)
library(parallel)
library(rgeos)
library(cleangeo)

# NLCD MT raster
mt_nlcd <- raster("../R_output_files/nlcd/mt_nlcd_270.tif")

# Montana Outline
mt_outline <- read_sf("../R_input_files/mt_outline/StateofMontana.shp") %>% 
  st_transform(.,crs(mt_nlcd))

# Montana Counties
mt_counties <- read_sf("../R_input_files/mt_counties/County.shp") %>% 
  st_transform(.,crs(mt_nlcd)) %>% 
  dplyr::select(NAME)
```

### 2. Wilderness Areas
```{r packages_data}
# Wilderness Areas for the National Wilderness Preservation System Database
wilderness <- read_sf("../R_input_files/Wilderness_Areas/Wilderness_Areas_103019.shp") %>% 
  st_transform(.,crs(mt_nlcd)) %>% 
  filter(str_detect(STATE,"MT")) %>% 
  summarise() %>% 
  as(.,"Spatial") %>% 
  disaggregate() %>% 
  st_as_sf() %>% 
  dplyr::select() %>% 
  mutate("category" = "wilderness",
    "object_id" = paste0(1:nrow(.),"_wild"))

```

### 3. Protected Areas Database (PAD) GAP Core Areas
```{r pad_gap}

# Protected Areas Database 
pad <- read_sf("../R_input_files/mt_pad/PAD_combined_clean.shp") %>%
  st_transform(.,crs(mt_nlcd)) %>% 
  st_simplify()

# Filter for GAP 1 or 2 parcels -- parcels that manage for biodiversity
pad_gap <- pad %>% 
  filter(GAP_Sts %in% c(1,2)|(GAP_Sts == 3 & Mang_Name == 'NPS')) %>% # Filter for polygons that are managed for biodiversity 
  group_by(GAP_Sts) %>% # Group by status
  summarise() %>% # Combine those that have the same status
  st_buffer(.,200) %>% # Buffer to solve weird geometry issues
  as(.,"Spatial") %>% 
  disaggregate(.) %>%
  st_as_sf() %>% 
  st_buffer(.,-200 ) %>% 
  dplyr::select() %>% 
  mutate("category" = "pad_gap",
    "object_id" = paste0(1:nrow(.),"_gap"))

# Join with wilderness polygons
# Join PAD GAP 1 & 2 with fish and wildlife polygons
wild_gap_join = st_join(wilderness, pad_gap, left = T, largest = T)
 
# Get list of PAD polygons that joined with PAD data
joined_padIDs = na.omit(wild_gap_join$object_id.y)

# Clean up joined data set -- anything that joined will take the ID of the Gap Status Polygon
wild_gap_join = dplyr::select(wild_gap_join,-c(category.y,object_id.y)) # Remove columns from join associated with PAD data
colnames(wild_gap_join)[1:2]= c("category","object_id")

# From the PAD dataset, filter out observations that have already joined with the wilderness dataset
pad_gap_fltr = filter(pad_gap,!(object_id %in% joined_padIDs))

# Combine the joined data set with the PAD Access parcels that did not join.
wild_gap_final = rbind(wild_gap_join,pad_gap_fltr)
```

### 4. Fish and Wildlife 
```{r fishandwildlife}
# Montana Fish, Wildlife, and Parks Land Parcels
fwp = read_sf("../R_input_files/MT_FWP_Lands_Parcels_shp/020b61ed-402c-4012-8e4c-2bf60a7cd0fe202047-1-pd7i66.tiob.shp") %>% 
  st_transform(.,crs(mt_nlcd)) %>% 
  filter(!SITETYPE %in% c("FAS","HTC")) %>% # Remove fishing access sites and fish hatcheries
  st_buffer(.,200) %>% # Workaround to fix geometry that results from weird/convoluted boundaries 
  summarise() %>% # Combine polygons with the same site id
  as(.,"Spatial") %>% 
  disaggregate() %>% 
  st_as_sf() %>% 
  st_buffer(.,-200) %>% # Undo buffer
  dplyr::select() %>% # remove all attributes other than geometry
  mutate("category" = "fishwildlifeparks", # Create attributes for the compiled dataset
    "object_id" = paste0(1:nrow(.),"_fwp"))

# Join wilderness/PAD GAP with fish and wildlife polygons
wildgap_fwp_join = st_join(wild_gap_final, fwp, left = T, largest = T)

# Get list of fish and wildlife polygons that joined with wild/PAD data
joined_fwpIDs = na.omit(wildgap_fwp_join$object_id.y)

# Clean up joined data set -- anything that joined will take the ID of the Gap Status Polygon
wildgap_fwp_join = dplyr::select(wildgap_fwp_join,-c(category.y,object_id.y)) # Remove columns from join associated with access data
colnames(wildgap_fwp_join)[1:2]= c("category","object_id")

# Filter out fish and wildlife polygons that joined with the wild/GAP data set
fwp_fltr = filter(fwp,!(object_id %in% joined_fwpIDs))

# Combine the joined data set with the PAD Access parcels that did not join.
wildgapfwp_final = rbind(wildgap_fwp_join,fwp_fltr)

```

### 5. Adding in Conservation Easements
```{r conservation_easements}

# Conservation Easements
cons_easements = read_sf("../R_input_files/ConEasements/ConEasements_clean.shp") %>% 
  st_transform(.,crs(mt_nlcd)) %>% 
  dplyr::select() %>% 
  # st_buffer(.,200) %>% # Workaround to fix geometry that results from weird/convoluted boundaries
  # st_buffer(.,-200) %>% 
  summarise() %>% 
  as(.,"Spatial") %>% 
  disaggregate() %>% 
  st_as_sf() %>% 
  mutate("category" = "conservation_easement",
    "object_id" = paste0(1:nrow(.),"_consease")) 
  
# Join Final PAD core areas with conservation easement core areas
wildgapfwp_consease_join = st_join(wildgapfwp_final,cons_easements, left = T, largest = T)

# Get list of Conservation Easement polygons that joined with PAD data
joined_conseaseIDs = na.omit(wildgapfwp_consease_join$object_id.y)

# Clean up joined data set -- anything that joined will take the ID of the Gap Status Polygon
wildgapfwp_consease_join = dplyr::select(wildgapfwp_consease_join,-c(category.y,object_id.y)) # Remove columns from join associated with access data

colnames(wildgapfwp_consease_join)[1:2]= c("category","object_id")

# Filter out Conservation Easement parcels that joined with the GAP data set
consease_fltr = filter(cons_easements,!(object_id %in% joined_conseaseIDs))

# Combine the joined data set with the PAD Access parcels that did not join.
wildgapfwpconsease_final = rbind(wildgapfwp_consease_join,consease_fltr)

# Empty geometry fixing
wildgapfwpconsease_final$empty_geos = as.factor(is.na(st_dimension(wildgapfwpconsease_final))) # find which one is empty
wildgapfwpconsease_final = filter(wildgapfwpconsease_final,empty_geos=="FALSE") %>%  # Filter out the empty one and remove the extra column
  dplyr::select(-empty_geos)


writeOGR(as(wildgapfwpconsease_final,"Spatial"),
         dsn = "../R_output_files/scratch/",
         layer = "wildgapfwpconsease",
         driver = "ESRI Shapefile",
         overwrite_layer = T)
    
```

### 6. Adding in Protected Area Database Restricted Access parcels
```{r pad_access}
## Create another set of polygons based on the "Access" column -- rationale is that many of these are manage or used a research for biodiversity, and many relatively natural places with closed or restricted access serve has habitat
pad_access = pad %>% 
  filter(d_Access %in% c("Restricted Access","Closed") & !d_Des_Tp %in% c("Agricultural Easement",
                                                                          "Private Agriculture",
                                                                          "Ranch Easement")) %>% 
  group_by(d_Access) %>% # Select access column
  summarise() %>% # Combine polygons based on the d_Access factor level
  st_buffer(.,200) %>% # Buffer to mitigate spatial issues that arise from complicated/convoluted polygon shapes
  as(.,"Spatial") %>% # Convert to shapefile
  disaggregate(.) %>% # Separate polygons that are not spatially connected
  st_as_sf() %>% # Turn back into spatial dataframe
  st_buffer(.,-200) %>% # remove the buffer
  dplyr::select() %>% # get rid of all non-geometry columns
  mutate("category" = "pad_access", # generate two new columns that contain the category and a unique ID
    "object_id" = paste0(1:nrow(.),"_access"))

# Spatial join between GAP and access data sets
all_join = st_join(wildgapfwpconsease_final, pad_access, left = T, largest = T)

# Get a list of the Access object IDs that joined to the GAP data set
joined_accessIDs = na.omit(all_join$object_id.y)

# Clean up joined data set -- anything that joined will take the ID of the Gap Status Polygon
all_join = dplyr::select(all_join,-c(category.y,object_id.y)) # Remove columns from join associated with access data

colnames(all_join)[1:2]= c("category","object_id")

# Filter out PAD Access parcels that joined with the GAP data set
pad_access_fltr = filter(pad_access,!object_id %in% joined_accessIDs)

# Combine the joined data set with the PAD Access parcels that did not join. 
all_final = rbind(all_join,pad_access_fltr)

all_final$area = as.numeric(st_area(all_final))
all_final$mt_core_id = 1:nrow(all_final)

# Write shapefile to check
writeOGR(as(all_final,"Spatial"),
         dsn = "../R_output_files/circuitscape/core_area_shapefiles/MONTANA/",
         "MONTANA_coreareas",
         "ESRI Shapefile",
         overwrite_layer = T)

```

### 7. Function to crop Core Areas SF to counties
```{r create_county_core_area_function}


coreareas_fun = function(county_name, core_quality_table, shapefile = T, raster_nodes = T){
  
  print(county_name)
  
  county_i = filter(mt_counties, NAME == county_name) %>% 
    dplyr::select(NAME) %>% 
    as(.,"Spatial")
  
  core_areas = st_as_sf(core_areas) %>% 
    st_buffer(.,5) %>% 
    as(.,"Spatial")
  
  county_i_cores = raster::intersect(core_areas,county_i) %>% # Crop core areas to county
    st_as_sf() # Turn into spatial data frame  
    
  # Merge Core Areas SF with core quality table
  county_i_cores_merge = merge(county_i_cores,core_quality_table)
  
  county_i_cores_merge$core_quality = county_i_cores_merge$area*county_i_cores_merge$multiplier
  
  county_i_cores_final <<- county_i_cores_merge %>% 
    arrange(-core_quality) %>% 
    head(5)
  
  county_i_cores_final$core_id = 1:nrow(county_i_cores_final)
  
  if(shapefile){
  
  writeOGR(as(county_i_cores_final,"Spatial"),
           paste0("../R_output_files/circuitscape/core_area_shapefiles/",county_name),
           paste0(county_name,"_coreareas_final"),
           "ESRI Shapefile",
           overwrite_layer = T)
    
  }
  
  if(raster_nodes){
    
    core_centroids = st_centroid(x = county_i_cores_final)
    core_nodes <<- rasterize(x = core_centroids,y = mt_nlcd, field = "core_id")
    NAvalue(core_nodes) = -9999
    
    writeRaster(core_nodes,paste0("../R_output_files/circuitscape/core_node_asciis/",
                                  county_name,"_corenodes.asc"), format = "ascii", overwrite = T)
    
  }
  
}

```

### 8. Apply function
```{r apply_core_area_function}

# Need polygons for Linkage Mapper and Marxan (core polys)
# Rasterized centroids for Circuitscape (core nodes)
core_areas = readOGR("../R_output_files/circuitscape/core_area_shapefiles/MONTANA/MONTANA_coreareas.shp")

# Loop through all counties
county_names = as.list(mt_counties$NAME)

# Choose one county to create core areas for
# county_names = "CUSTER"

core_quality_table = data.frame(category = c("wilderness","pad_gap","fishwildlifeparks","conservation_easement","pad_access"),
                                multiplier = c(5,4,3,2,1)) ## Do more digging about how these lands are managed to decide


for(i in 1:length(county_names)){
  
  county_name = county_names[i]
  
  coreareas_fun(county_name = county_name, core_quality_table = core_quality_table, raster_nodes = F)
  
}

```

Merge MT counties with core areas sf
```{r}

coreareas_county_merge = st_join(x = core_areas,y = mt_counties) %>% 
  merge(core_quality_table) %>% 
  mutate(weighted_area = area*multiplier) %>% 
  arrange(-weighted_area) %>% 
  group_by(NAME) %>% 
  slice(1:5)

montana_cores = st_as_sf(core_areas) %>% 
  st_buffer(.,5) %>% 
  as(.,"Spatial") %>% 
  raster::intersect(.,mt_outline) %>% # Crop core areas to county
  st_as_sf() # Turn into spatial data frame  

writeOGR(as(coreareas_county_merge,"Spatial"),
           "../R_output_files/circuitscape/core_area_shapefiles/MONTANA/",
           "Montana_top5county_coreareas",
           "ESRI Shapefile",
           overwrite_layer = T)

coreareas_county_merge_df = as.data.frame(coreareas_county_merge) %>% dplyr::select(-geometry)
colnames(coreareas_county_merge)

```

